from enum import Enum, auto


class T_nont(Enum):
    PROGRAMA_ = 0
    LISTA_DECLARACOES_EXTERNAS_ = auto()
    DECLARACAO_EXTERNA_ = auto()
    TIPO_ = auto()
    DECLARACAO_TIPO_ = auto()
    DECLARACAO_CAMPOS_ = auto()
    DECLARACAO_FUNCAO_ = auto()
    NEW_BLOCK_ = auto()
    N_FUNCAO_ = auto()
    MARCADOR_FUNCAO_ = auto()
    MARCADOR_C_ = auto()
    LISTA_PARAMETROS_ = auto()
    BLOCO_ = auto()
    LISTA_DECLARACAO_VARIAVEIS_ = auto()
    LISTA_COMANDOS_ = auto()
    DECLARACAO_VARIAVEL_ = auto()
    LISTA_IDENTIFICADORES_ = auto()
    MT_ = auto()
    ME_ = auto()
    MW_ = auto()
    COMANDO_ = auto()
    EXPRESSAO_ = auto()
    EXPRESSAO_L_ = auto()
    EXPRESSAO_R_ = auto()
    EXPRESSAO_Y_ = auto()
    EXPRESSAO_F_ = auto()
    LISTA_EXPRESSOES_ = auto()
    VALOR_ESQUERDO_ = auto()
    IDD_ = auto()
    IDU_ = auto()
    ID_ = auto()
    TRUE_ = auto()
    FALSE_ = auto()
    CHR_ = auto()
    STR_ = auto()
    NUM_ = auto()