from enum import Enum, auto


class T_rule(Enum):
    START = 0                                   # 0    S' -> programa
    PROGRAMA = auto()                           # 1    programa -> lista_declaracoes_externas
    LISTA_DECLARACOES_EXTERNAS = auto()         # 2    lista_declaracoes_externas -> declaracao_externa
    LISTA_DECLARACOES_EXTERNAS_REC = auto()     # 3    lista_declaracoes_externas -> lista_declaracoes_externas declaracao_externa
    DECLARACAO_EXTERNA_TIPO = auto()            # 4    declaracao_externa -> declaracao_tipo
    DECLARACAO_EXTERNA_FUNCAO = auto()          # 5    declaracao_externa -> declaracao_funcao
    DECLARACAO_EXTERNA_VARIAVEL = auto()        # 6    declaracao_externa -> declaracao_variavel
    TIPO_INTEGER = auto()                       # 7    tipo -> INTEGER
    TIPO_CHAR = auto()                          # 8    tipo -> CHAR
    TIPO_BOOLEAN = auto()                       # 9    tipo -> BOOLEAN
    TIPO_STRING = auto()                        # 10   tipo -> STRING
    TIPO_IDU = auto()                           # 11   tipo -> idu
    DECLARACAO_TIPO_ARRAY = auto()              # 12   declaracao_tipo -> TYPE idd EQUALS ARRAY LEFT_SQUARE num RIGHT_SQUARE OF tipo
    DECLARACAO_TIPO_STRUCT = auto()             # 13   declaracao_tipo -> TYPE idd EQUALS STRUCT new_block LEFT_BRACES declaracao_campos RIGHT_BRACES
    DECLARACAO_TIPO = auto()                    # 14   declaracao_tipo -> TYPE idd EQUALS tipo
    DECLARACAO_CAMPOS_REC = auto()              # 15   declaracao_campos -> declaracao_campos SEMI_COLON lista_identificadores COLON tipo
    DECLARACAO_CAMPOS = auto()                  # 16   declaracao_campos -> lista_identificadores COLON tipo
    DECLARACAO_FUNCAO = auto()                  # 17   declaracao_funcao -> FUNCTION idd new_block LEFT_PARENTHESIS lista_parametros RIGHT_PARENTHESIS COLON tipo bloco
    NEW_BLOCK = auto()                          # 18   new_block -> <empty>
    LISTA_PARAMETROS_REC = auto()               # 19   lista_parametros -> lista_parametros COMMA idd COLON tipo
    LISTA_PARAMETROS = auto()                   # 20   lista_parametros -> idd COLON tipo
    BLOCO = auto()                              # 21   bloco -> LEFT_BRACES lista_declaracao_variaveis lista_comandos RIGHT_BRACES
    LISTA_DECLARACAO_VARIAVEIS_REC = auto()     # 22   lista_declaracao_variaveis -> lista_declaracao_variaveis declaracao_variavel
    LISTA_DECLARACAO_VARIAVEIS = auto()         # 23   lista_declaracao_variaveis -> declaracao_variavel
    LISTA_COMANDOS_REC = auto()                 # 24   lista_comandos -> lista_comandos comando
    LISTA_COMANDOS = auto()                     # 25   lista_comandos -> comando
    DECLARACAO_VARIAVEL = auto()                # 26   declaracao_variavel -> VAR lista_identificadores COLON tipo SEMI_COLON
    LISTA_IDENTIFICADORES_REC = auto()          # 26   lista_identificadores -> lista_identificadores COMMA idd
    LISTA_IDENTIFICADORES = auto()              # 27   lista_identificadores -> idd
    COMANDO_IF = auto()                         # 28   comando -> IF LEFT_PARENTHESIS expressao RIGHT_PARENTHESIS comando
    COMANDO_IF_ELSE = auto()                    # 29   comando -> IF LEFT_PARENTHESIS expressao RIGHT_PARENTHESIS comando ELSE comando
    COMANDO_WHILE = auto()                      # 30   comando -> WHILE LEFT_PARENTHESIS expressao RIGHT_PARENTHESIS comando
    COMANDO_DO = auto()                         # 31   comando -> DO commando WHILE LEFT_PARENTHESIS expressao RIGHT_PARENTHESIS SEMI_COLON
    COMANDO_BLOCO = auto()                      # 32   comando -> bloco
    COMANDO_LEFT_VALUE_EQUALS = auto()          # 33   comando -> valor_esquerdo EQUALS expressao SEMI_COLON
    COMANDO_BREAK = auto()                      # 34   comando -> BREAK SEMI_COLON
    COMANDO_CONTINUE = auto()                   # 35   comando -> CONTINUE SEMI_COLON
    EXPRESSAO_AND = auto()                      # 36   expressao -> expressao AND expressao_l
    EXPRESSAO_OR = auto()                       # 37   expressao -> expressao OR expressao_l
    EXPRESSAO = auto()                          # 38   expressao -> expressao_l
    EXPRESSAO_L_LESS_THAN = auto()              # 39   expressao_l -> expressao_l LESS_THAN expressao_r
    EXPRESSAO_L_LESS_OR_EQUAL = auto()          # 40   expressao_l -> expressao_l LESS_OR_EQUAL expressao_r
    EXPRESSAO_L_GREATER_THAN = auto()           # 41   expressao_l -> expressao_l GREATER_THAN expressao_r
    EXPRESSAO_L_GREATER_OR_EQUAL = auto()       # 42   expressao_l -> expressao_l GREATER_OR_EQUAL expressao_r
    EXPRESSAO_L_EQUAL_EQUAL = auto()            # 43   expressao_l -> expressao_l EQUAL_EQUAL expressao_r
    EXPRESSAO_L_NOT_EQUAL = auto()              # 44   expressao_l -> expressao_l NOT_EQUAL expressao_r
    EXPRESSAO_L_R = auto()                      # 45   expressao_l -> expressao_r
    EXPRESSAO_R_PLUS = auto()                   # 46   expressao_r -> expressao_r PLUS expressao_y
    EXPRESSAO_R_MINUS = auto()                  # 47   expressao_r -> expressao_r MINUS expressao_y
    EXPRESSAO_R_Y = auto()                      # 48   expressao_r -> expressao_y
    EXPRESSAO_Y_TIMES = auto()                  # 49   expressao_y -> expressao_y TIMES expressao_f
    EXPRESSAO_Y_DIVIDE = auto()                 # 50   expressao_y -> expressao_y DIVIDE expressao_f
    EXPRESSAO_Y = auto()                        # 51   expressao_y -> expressao_f
    EXPRESSAO_F_LEFT_VALUE = auto()             # 52   expressao_f -> valor_esquerdo
    EXPRESSAO_F_PLUS_PLUS_LEFT_VALUE = auto()   # 53   expressao_f -> PLUS_PLUS valor_esquerdo
    EXPRESSAO_F_MINUS_MINUS_LEFT_VALUE = auto() # 54   expressao_f -> MINUS_MINUS valor_esquerdo
    EXPRESSAO_F_LEFT_VALUE_PLUS_PLUS = auto()   # 55   expressao_f -> valor_esquerdo PLUS_PLUS
    EXPRESSAO_F_LEFT_VALUE_MINUS_MINUS = auto() # 56   expressao_f -> valor_esquerdo MINUS_MINUS
    EXPRESSAO_F_LEFT_PARENTHESIS = auto()       # 57   expressao_f -> LEFT_PARENTHESIS expressao RIGHT_PARENTHESIS
    EXPRESSAO_F_IDU_LEFT_PARENTHESIS = auto()   # 58   expressao_f -> idd LEFT_PARENTHESIS lista_expressoes RIGHT_PARENTHESIS
    EXPRESSAO_F_MINUS = auto()                  # 59   expressao_f -> MINUS expressao_f
    EXPRESSAO_F_NOT = auto()                    # 60   expressao_f -> NOT expressao_f
    EXPRESSAO_F_TRUE = auto()                   # 61   expressao_f -> true
    EXPRESSAO_F_FALSE = auto()                  # 62   expressao_f -> false
    EXPRESSAO_F_CHARACTER = auto()              # 63   expressao_f -> chr
    EXPRESSAO_F_STRINGVAL = auto()              # 64   expressao_f -> str
    EXPRESSAO_F_NUMERAL = auto()                # 65   expressao_f -> num
    LISTA_EXPRESSOES_REC = auto()               # 66   lista_expressoes -> lista_expressoes COMMA expressao
    LISTA_EXPRESSOES = auto()                   # 67   lista_expressoes -> expressao
    VALOR_ESQUERDO_DOT = auto()                 # 68   valor_esquerdo -> valor_esquerdo DOT id
    VALOR_ESQUERDO_LEFT_SQUARE = auto()         # 69   valor_esquerdo -> valor_esquerdo LEFT_SQUARE expressao RIGHT_SQUARE
    VALOR_ESQUERDO_IDU = auto()                 # 70   valor_esquerdo -> idu
    IDD = auto()                               # 71   idd -> ID
    IDU = auto()                               # 72   idu -> ID
    ID = auto()                                # 73   id -> ID
    TRUE = auto()                              # 74   true -> TRUE
    FALSE = auto()                             # 75   false -> FALSE
    CHR = auto()                               # 76   chr -> CHARACTER
    STR = auto()                               # 77   str -> STRINGVAL
    NUM = auto()                               # 78   num -> NUMERAL